levxyca/diciotech

index.html, style.css
[WIP] Implementação do novo layout desenvolvido pelo @rafaeldellaquila 😁
- searchbar ainda sem funcionalidade 🛑
- cores e fonte podem não ser as mesma do layout 🚨
=> :sparkles: implementação do novo layout by @rafaeldellaquila

assets/js/script.js
Percebi que podia ter uma refatoração no mecanismo de busca, então fiz a refatoração para melhor legibilidade do código e desempenho.
=> refatoração no search

assets/data/cards_pt-br.json, assets/js/script.js, index.html
- Anteriormente as inserções dos cards eram realizadas de forma manual, no arquivo `index.html`, mas agora é inserido através de requisição JSON do arquivo `cards_pt-br.json`, presente na pasta "data".
> Com essa refatoração muitas opções se abrem para o projeto, como traduções.
=> refactor: inserção de cards com requisição JSON

assets/css/style.css, assets/js/script.js
Anteriormente as inserções das cartas eram realizadas de forma sequencial, conforme a estrutura do JSON com os dados, mas agora os mesmos são inseridos em ordem alfabética, facilitando a busca e a visualização dos conteúdos. A função `sortCardsByTitle` é responsável por essa ordenação.
=> feat: sort cards

assets/css/style.css, assets/data/cards_pt-br.json
Foi editado os cards fazendo com que todos tenham o mesmo tamanho base, mas caso o texto seja maior que os cards, eles se adaptem ao tamanho do texto.
=> Cards Responsivos

assets/data/cards_pt-br.json
Neste PR 8 novos termos foram adicionados ao arquivo "cards_pt-br".
- Função;
- Argumento;
- Programação orientada a objetos;
- Classe;
- Objeto;
- Encapsulamento;
- Herança;
- Polimorfismo;
=> adicionando termos relacionados a POO

assets/data/cards_pt-br.json
- Desenvolvimento Front-end
- HTML
- CSS
- JavaScript
- jQuery
- UI Design
- UX Design
- Frameworks
=> Adicionado novos termos

assets/css/style.css, assets/css/var.css, assets/data/cards_pt-br.json, assets/js/script.js, index.html
**Aqui estão algumas melhorias implementadas no código:**
- **Grid de 8 pontos:** Adotamos uma grade de 8 pontos para melhorar a estrutura do layout. Você pode encontrar mais informações sobre essa abordagem no meu blog [aqui](https://iuricode-blog.vercel.app/posts/grid-de-8-pontos-uma-tecnica-que-torna-seu-projeto-escalavel).
- **Tamanho da fonte ajustado para 62,5%:** Para otimizar a legibilidade, ajustamos o tamanho da fonte para 62,5%. Uma explicação detalhada sobre essa técnica pode ser encontrada em uma postagem no meu Instagram [aqui](https://www.instagram.com/p/CwVgMPhrcy_).
**Além dessas modificações, realizamos melhorias visuais no projeto, que incluem:**
- **Responsividade aprimorada:** Corrigimos o problema de grande espaçamento nos cards na versão móvel. Agora, eles se …
=> :ok_hand: style: Alterações de revisão de código

assets/data/cards_pt-br.json
=> new-term: Recursão

assets/js/dark_mode.js
- Theme persistence has been added to the project.
=> feat: Adding theme state persistence to the application.

assets/data/cards_pt-br.json
Novo termo adicionado. 🖤
Closes #59
=> new: adição do termo bug

assets/data/cards_pt-br.json
De acordo com o reply do @iuricode no PR #38, a feature do filtro realmente parece estar um pouco extensa. Nesse caso, alterei algumas das tags dos termos em busca de um maior refinamento na filtragem dos cards, conforme sugerido, como por exemplo a remoção das opções "CSS e JavaScript", que acabam que estão incluídas no conjunto "Front-end".
Além disso, corrigi alguns erros de pontuação e ortografia que estavam presentes em alguns dos termos.
=> feat: pontuação dos termos e algumas tags ajustadas

assets/data/cards_pt-br.json
Estou adicionando o termo python para o back-end.
=> new: adição do termo python

LICENSE
Adicionei a licença v3 da GNU General public license
=> feat: adding GNU General public license v3

CONTRIBUTING.md
Atualiza o [CONTRIBUTING.md](https://github.com/levxyca/diciotech/blob/main/CONTRIBUTING.md) para atender a nova feature de filtro por tags e adiciona a orientação para sugerir novas tags.
Este pull request resolve a issue #70.
=> docs(CONTRIBUTING): atualiza a documentação de contribuição para atender tags

assets/data/cards_pt-br.json
Olá 👋 
parabéns pelo projeto, acho que vou focar meu hacktoberfest todo por aqui esse ano adicionando novos termos! 
Pensei em algo genérico para começar, mas quero ver de adicionar algumas coisas mais específicas também depois.
=> Novo termo 'cache'

assets/data/cards_pt-br.json
Adicionando novos termos no dicionário:
- Ambiente (local, dev, homologação e produção);
- API;
- Code Review;
- Commit;
- Deploy;
- Json;
- Pair Programming;
- Pull Request.
Qualquer problema ou sugestão, fico à disposição.
Closes #101
=> adicionando novos termos técnicos ao diciotech

assets/data/cards_pt-br.json
#106  - Removi o termo Mobile First duplicado e reescrevi o original, melhorando o entendimento do mesmo.
=> Remove duplicate Mobile First term and rewrite him

assets/data/cards_pt-br.json
Adicionando conceito da linguagem de programação Ruby.
=> Add conceito Ruby

assets/data/cards_pt-br.json
Oii! Fiz as atualizações :)
Sou iniciante com git e github, desculpe a confusão kk
=> Adicionando os termos: bd, bd relacional, nosql e lambda

assets/data/cards_pt-br.json
Adicionando uma breve introdução sobre **code smells** na categoria **Conceito**.
=> feat: adicionando conceito, code smells

.github/pull_request_template.md
Cria um novo modelo de PR, com instruções em comentários e cabeçalhos pré-definidos para o contribuidor. Os comentários serão renderizados apenas no campo de texto, e não aparecem no Preview do PR. 
Eu tentei colocar em Yaml, no estilo formulário, mas não consegui ~ainda~. Abri o PR para deixar a decisão em aberto: 
1- Podemos mesclar este modelo em Markdown, que é funcional - e seguir testando o formulário
2 - Podemos esperar um pouco mais na minha investigação para implementar o formulário definitivamente.
Eu votaria pela primeira opção, seguindo o princípio de entrega, depois melhora. Mas acredito que não demore muito até descobrir se é possível e como fazer. Menos que o atual _delay_ na resolução ~sorry~.
- #93 
Conforme discussão do #93, começamos com um modelo simples de Pull …
=> Cria modelo de PR para o projeto

assets/data/cards_pt-br.json
Explicação sobre os princípios SOLID
=> Feat: Principios SOLID

assets/data/cards_pt-br.json
Correção com a remoção dos termos duplicados `Branch` e `Pull Request`, mantendo os termos que julguei serem os mais completos. Também adicionei a Tag "Versionamento" ao Card de `Pull Request` que ficou, pois não tinha.
Cards mantidos:
- Branch -> linha `184` do arquivo `cards_pt-br.json`
- Pull Request -> linha `350` do arquivo `cards_pt-br.json`
- #178 
Estou acompanhando o projeto a algum tempo e acho que esse pequeno detalhe pode ser um bom jeito de contribuir. Ainda não tenho muito o que agregar em termos de conhecimento ou aprimoramento do sistema, mas me interesso muito pelo projeto.
Sem novas infos
=> Fix duplicatas

assets/data/cards_pt-br.json
- Adição da descrição do ataque DOS, de Botnet  e do ataque DDOS, como os três assuntos se correlacionam achei mais coeso adicionar os assuntos na mesma PR .
- #184 
- Com os recentes ataques aos sites do governo estes assuntos estão mais presentes na mídia.
=> Feat: adição dos termos DOS, DDOS, BOTNET's

CONTRIBUTING.md
Alterações na seção do ambiente de desenvolvimento: 
-  Adicionou seção pra indicar como utilizar o Github.Dev pra fazer alterações em .md
-  Adicionou seção para indicar como realizar alterações visuais
- #195
=> Realizando alterações na documentação

assets/data/cards_pt-br.json
Adicionados termos de Design: Design System, Style Guide, Material, Design Ops e Design Critique.
Modificado os termos de UX e UI Design.
Adicionei os termos de design porque senti que faltava ;)
=> Adicionados termos de Design

assets/data/cards_pt-br.json
- #208 
RPA é um termo que eu tenho bastante contato no trabalho e não encontrei ele entre os termos já cadastrados, acredito que será util.
=> Adicionado o termo RPA

assets/data/cards_pt-br.json
Adicionados termos MLOps, DevOps, CD e modificado CI.
Percebi que o conceito de CI estava bem simples e aproveitei pra adicionar alguns relacionados. Acho que é sempre bom adicionar o termo em inglês e a sigla na descrição, ajuda a achar caso faça uma busca pela sigla ou termo em inglês.
=> Adicionados termos MLOps, DevOps, CI e CD

assets/css/dark_mode.css, assets/css/style.css, assets/js/script.js
Ajuste do bug : https://github.com/levxyca/diciotech/issues/201
Altera o ícone "https://img.icons8.com/ios-glyphs/30/ffe100/star--v1.png" de imagem para icone da lib https://phosphoricons.com/
=> Ajuste do icone de favorito

format_data.py
Garante que a descrição dos termos do dicionário termina com um `.`
- Resolve #252
Padronizar as descrições
=> Garante que a descrição termina com um ponto final

assets/data/cards_pt-br.json
Adicionando explicação do termo Laravel
- #274
=> Adicionando explicação do termo Laravel

assets/data/cards_pt-br.json
Explicando termos da Issue relacionado. Tomei a liberdade de remover a explicação de CMD para a explicação genérica de Terminal! 
- #278
=> Solves #278

_scripts/localized_scripts.js.liquid, assets/js/cards.js
Resolve o filtro por tag
- Resolve #300
=> Resolve o filtro por tag

_data/en-us/strings.yml, _data/pt-br/strings.yml, _layouts/base.liquid, _sass/base.scss, _sass/dark_theme.scss, _sass/light_theme.scss, assets/js/scrollButton.js
- #148
A motivação dessa alteração é contribuir com open source
Essa PR adiciona um botão que retorna para o topo da página. Segue gif do comportamento:
=> feat: create a button top

_sass/base.scss, assets/js/scrollButton.js
Run prettier for the files:
`_sass/base.scss`
`assets/js/scrollButton.js`
#311
=> chore: run prettier
